import {
  amberDark,
  blueDark,
  brownDark,
  crimsonDark,
  cyanDark,
  grassDark,
  greenDark,
  indigoDark,
  limeDark,
  mauveDark,
  mintDark,
  orangeDark,
  pinkDark,
  plumDark,
  purpleDark,
  redDark,
  skyDark,
  tealDark,
  tomatoDark,
  violetDark,
  yellowDark,
} from '@radix-ui/colors'

const gray = {
  gray1: mauveDark.mauve1,
  gray2: mauveDark.mauve2,
  gray3: mauveDark.mauve3,
  gray4: mauveDark.mauve4,
  gray5: mauveDark.mauve5,
  gray6: mauveDark.mauve6,
  gray7: mauveDark.mauve7,
  gray8: mauveDark.mauve8,
  gray9: mauveDark.mauve9,
  gray10: mauveDark.mauve10,
  gray11: mauveDark.mauve11,
  gray12: mauveDark.mauve12,
}

export const dark = {
  ...amberDark,
  ...blueDark,
  ...brownDark,
  ...crimsonDark,
  ...cyanDark,
  ...grassDark,
  ...gray,
  ...greenDark,
  ...indigoDark,
  ...limeDark,
  ...mintDark,
  ...orangeDark,
  ...pinkDark,
  ...plumDark,
  ...purpleDark,
  ...redDark,
  ...skyDark,
  ...tealDark,
  ...tomatoDark,
  ...violetDark,
  ...yellowDark,

  primary1: '',
  primary2: '',
  primary3: '',
  primary4: '',
  primary5: '',
  primary6: '',
  primary7: '',
  primary8: '',
  primary9: '',
  primary10: '',
  primary11: '',
  primary12: '',

  white: '#ffffff',
  black: '#000000',

  appBackground: '$gray1',
  textTitle: '$gray12',
  shape: '$gray3',
}
